# Generated by Django 5.2.5 on 2025-08-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_product_color_alter_product_sizes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rating',
            new_name='ratings',
        ),
    ]
